-- Golden/SQL*Plus 관용 예시 (사용자 제공) — 세션 변수를 여러 문장이 공유한다
EXEC	:V_PRG_NM			:=	'SP_M4P_MPO_M4E_CREATE_BSY';

EXEC DBMS_STATS.GATHER_TABLE_STATS(USER, 'M4E_I301080', CASCADE=>TRUE, NO_INVALIDATE=>FALSE);

EXEC SP_M4P_MP_VERSION_CREATE(:PC_RET, 'SEBANG', 'DP_202604_W16_V01', 'W', '20260415', '20260705', '', 'sybae0057');


--	MP 버전에 기반한 변수 설정
EXEC
SELECT
	A.PROJECT_CD
,	A.MP_VRSN_ID
,	A.MP_VRSN_SEQ
,	A.DP_VRSN_ID
,	A.PRGS_STA_CD
INTO
	:V_PROJECT_CD
,	:V_MP_VRSN_ID
,	:V_MP_VRSN_SEQ
,	:V_DP_VRSN_ID
,	:V_PRGS_STA_CD
FROM
	M4S_O301010 A
WHERE 1=1
AND	A.PROJECT_CD		=	'SEBANG'

SELECT
	:V_PROJECT_CD
,	:V_MP_VRSN_ID
,	:V_MP_VRSN_SEQ
,	:V_DP_VRSN_ID
,	:V_PRGS_STA_CD
,	:V_ENG_CD
,	:V_PRG_NM
,	:V_USER
FROM
	DUAL
;

connect user/pass@192.168.1.1:1521/db;
