-- Oracle 실기 스크립트(integration.yml · Codespaces): SQL*Plus 관용 그대로
SET SERVEROUTPUT ON
VARIABLE rc REFCURSOR
EXEC :V_USER := USER
EXEC :V_PRG_NM := 'SP_M4P_MPO_M4E_CREATE_BSY'
EXEC
SELECT COUNT(*), MAX(OBJECT_NAME)
INTO :V_CNT, :V_MAX
FROM ALL_OBJECTS
WHERE OWNER = 'SYS' AND ROWNUM <= 5

PRINT V_USER V_PRG_NM V_CNT V_MAX
SELECT :V_USER AS u, :V_PRG_NM AS prg, :V_CNT AS cnt FROM DUAL;
EXEC OPEN :rc FOR SELECT OBJECT_NAME FROM ALL_OBJECTS WHERE OWNER = 'SYS' AND ROWNUM <= 3
PRINT rc
EXEC DBMS_OUTPUT.PUT_LINE('done for ' || :V_USER)
